# Generated by Django 4.2 on 2026-04-09 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(default='Student Representative', max_length=100)),
                ('institution_type', models.CharField(choices=[('school', 'School'), ('pu', 'PU College'), ('engineering', 'Engineering College'), ('all', 'All Institutions')], default='all', max_length=20)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('manifesto', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('school', 'School'), ('pu', 'PU College'), ('engineering', 'Engineering College')], max_length=20)),
                ('student_id', models.CharField(help_text='Roll No / Reg No / USN', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('class_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Class')),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['institution_type', 'student_id'],
            },
        ),
        migrations.CreateModel(
            name='VoteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('user_id_hash', models.CharField(max_length=64)),
                ('candidate', models.CharField(max_length=100)),
                ('timestamp', models.FloatField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('block_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.student')),
            ],
            options={
                'verbose_name': 'Vote Block',
                'verbose_name_plural': 'Vote Blocks',
                'ordering': ['index'],
            },
        ),
    ]
